const LanguageList = [
"EN - English",
"CA - Català",
"CS - Čeština",
"DA - Dansk",
"DE - Deutsch",
"ES - Español",
"FR - Français",
"HR - Hrvatski",
"HU - Magyar",
"ID - bahasa Indonesia",
"IS - Íslenska",
"IT - Italiano",
"JP - 日本語",
"KAB - Taqbaylit",
"NL - Dutch",
"PL - Polski",
"PT - Português",
"PT-BR - Português do Brasil",
"RO - Română",
"RU - Pусский",
"SV - Svenska",
"TR - Türkçe",
"UA - Українська",
"ZH-Hans - 简体中文",
"ZH-Hant - 繁體中文",
"Help Translate",
]
export default LanguageList