import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <React.Fragment>

      <div>
      <h1>
                PERO
            </h1>  
            <h1>
                PERO
            </h1>     
            <h1>
                PERO
            </h1>      
            <h1>
                PERO
            </h1>  
            <h1>
                PERO
            </h1>     
            <h1>
                PERO
            </h1>      
            <h1>
                PERO
            </h1>  
            <h1>
                PERO
            </h1>     
            <h1>
                PERO
            </h1>      
            <h1>
                PERO
            </h1>  
            <h1>
                PERO
            </h1>     
            <h1>
                PERO
            </h1>      
            <h1>
                PERO
            </h1>  
            <h1>
                PERO
            </h1>     
            <h1>
                PERO
            </h1>      
            <h1>
                PERO
            </h1>  
            <h1>
                PERO
            </h1>     
            <h1>
                PERO
            </h1>      
            <h1>
                PERO
            </h1>  
            <h1>
                PERO
            </h1>     
            <h1>
                PERO
            </h1>      
            <h1>
                PERO
            </h1>  
            <h1>
                PERO
            </h1>     
            <h1>
                PERO
            </h1>      
            <h1>
                PERO
            </h1>  
            <h1>
                PERO
            </h1>     
            <h1>
                PERO
            </h1>      
            <h1>
                PERO
            </h1>  
            <h1>
                PERO
            </h1>     
            <h1>
                PERO
            </h1>      
            <h1>
                PERO
            </h1>  
            <h1>
                PERO
            </h1>     
            <h1>
                PERO
            </h1>  
        </div> 
      
    </React.Fragment>

   
  )
}
